apiVersion: v1
kind: ConfigMap
metadata:
  name: wms-database-config
  namespace: wms-system
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "wms_db"
  spring.jpa.properties.hibernate.default_schema: "public"
  spring.flyway.enabled: "true"
  spring.flyway.baseline-on-migrate: "true"

