apiVersion: v1
kind: Service
metadata:
  name: picking-service
  namespace: wms-system
  labels:
    app: picking-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: picking-service

