apiVersion: v1
kind: Service
metadata:
  name: returns-service
  namespace: wms-system
  labels:
    app: returns-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: returns-service

